=begin
#Telegram bot API

#This is a swagger defenition for [Telegram bot API](https://core.telegram.org/bots/api). 

OpenAPI spec version: 3.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for Teleswagger::GamesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GamesApi' do
  before do
    # run before each test
    @instance = Teleswagger::GamesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GamesApi' do
    it 'should create an instance of GamesApi' do
      expect(@instance).to be_instance_of(Teleswagger::GamesApi)
    end
  end

  # unit tests for get_game_high_scores
  # 
  # 
  # @param token bot&#39;s token to authorize the request
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :chat_id 
  # @option opts [Integer] :message_id 
  # @option opts [String] :inline_message_id 
  # @return [InlineResponse2008]
  describe 'get_game_high_scores test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for send_game
  # 
  # 
  # @param token bot&#39;s token to authorize the request
  # @param [Hash] opts the optional parameters
  # @option opts [SendGameBody] :body 
  # @return [ResponseMessage]
  describe 'send_game test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_game_score
  # 
  # 
  # @param token bot&#39;s token to authorize the request
  # @param user_id 
  # @param score 
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :force 
  # @option opts [BOOLEAN] :disable_edit_message 
  # @option opts [Integer] :chat_id 
  # @option opts [Integer] :message_id 
  # @option opts [String] :inline_message_id 
  # @return [InlineResponse2007]
  describe 'set_game_score test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
