=begin
#Telegram bot API

#This is a swagger defenition for [Telegram bot API](https://core.telegram.org/bots/api). 

OpenAPI spec version: 3.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for Teleswagger::InlineApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'InlineApi' do
  before do
    # run before each test
    @instance = Teleswagger::InlineApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineApi' do
    it 'should create an instance of InlineApi' do
      expect(@instance).to be_instance_of(Teleswagger::InlineApi)
    end
  end

  # unit tests for answer_inline_query
  # 
  # 
  # @param token bot&#39;s token to authorize the request
  # @param [Hash] opts the optional parameters
  # @option opts [AnswerInlineQueryBody] :body 
  # @return [ResponseBool]
  describe 'answer_inline_query test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
