=begin
#Telegram bot API

#This is a swagger defenition for [Telegram bot API](https://core.telegram.org/bots/api). 

OpenAPI spec version: 3.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for Teleswagger::PaymentsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PaymentsApi' do
  before do
    # run before each test
    @instance = Teleswagger::PaymentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentsApi' do
    it 'should create an instance of PaymentsApi' do
      expect(@instance).to be_instance_of(Teleswagger::PaymentsApi)
    end
  end

  # unit tests for answer_pre_checkout_query
  # 
  # 
  # @param token bot&#39;s token to authorize the request
  # @param pre_checkout_query_id 
  # @param ok 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :error_message 
  # @return [ResponseBool]
  describe 'answer_pre_checkout_query test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for answer_shipping_query
  # 
  # 
  # @param token bot&#39;s token to authorize the request
  # @param [Hash] opts the optional parameters
  # @option opts [AnswerShippingQueryBody] :body 
  # @return [ResponseMessage]
  describe 'answer_shipping_query test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for send_invoice
  # 
  # 
  # @param token bot&#39;s token to authorize the request
  # @param [Hash] opts the optional parameters
  # @option opts [SendInvoiceBody] :body 
  # @return [ResponseMessage]
  describe 'send_invoice test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
