=begin
#Telegram bot API

#This is a swagger defenition for [Telegram bot API](https://core.telegram.org/bots/api). 

OpenAPI spec version: 3.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for Teleswagger::UpdatesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'UpdatesApi' do
  before do
    # run before each test
    @instance = Teleswagger::UpdatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UpdatesApi' do
    it 'should create an instance of UpdatesApi' do
      expect(@instance).to be_instance_of(Teleswagger::UpdatesApi)
    end
  end

  # unit tests for delete_webhook
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @return [ResponseBool]
  describe 'delete_webhook test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_updates
  # 
  # 
  # @param token bot&#39;s token to authorize the request
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset 
  # @option opts [Integer] :limit 
  # @option opts [Integer] :timeout 
  # @option opts [Array<String>] :allowed_updates 
  # @return [ResponseUpdate]
  describe 'get_updates test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_webhook_info
  # 
  # 
  # @param [Hash] opts the optional parameters
  # @return [WebhookInfo]
  describe 'get_webhook_info test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_webhook
  # 
  # 
  # @param token bot&#39;s token to authorize the request
  # @param url 
  # @param [Hash] opts the optional parameters
  # @option opts [File] :certificate 
  # @option opts [Integer] :max_connections 
  # @option opts [Array<String>] :allowed_updates 
  # @return [ResponseBool]
  describe 'set_webhook test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
