=begin
#Telegram bot API

#This is a swagger defenition for [Telegram bot API](https://core.telegram.org/bots/api). 

OpenAPI spec version: 3.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'date'

module Teleswagger
  class AllowedUpdate
    
    MESSAGE = "message".freeze
    EDITED_MESSAGE = "edited_message".freeze
    CHANNEL_POST = "channel_post".freeze
    EDITED_CHANNEL_POST = "edited_channel_post".freeze
    INLINE_QUERY = "inline_query".freeze
    CHOSEN_INLINE_RESULT = "chosen_inline_result".freeze
    CALLBACK_QUERY = "callback_query".freeze
  end

end
