=begin
#Telegram bot API

#This is a swagger defenition for [Telegram bot API](https://core.telegram.org/bots/api). 

OpenAPI spec version: 3.6

Generated by: https://github.com/swagger-api/swagger-codegen.git

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

require 'date'

module Teleswagger
  class AllowedUpdate
    
    MESSAGE = "message".freeze
    EDITED_MESSAGE = "edited_message".freeze
    CHANNEL_POST = "channel_post".freeze
    EDITED_CHANNEL_POST = "edited_channel_post".freeze
    INLINE_QUERY = "inline_query".freeze
    CHOSEN_INLINE_RESULT = "chosen_inline_result".freeze
    CALLBACK_QUERY = "callback_query".freeze
    SHIPPING_QUERY = "shipping_query".freeze
    PRE_CHECKOUT_QUERY = "pre_checkout_query".freeze
  end

end
