=begin
#Telegram bot API

#This is a swagger defenition for [Telegram bot API](https://core.telegram.org/bots/api). 

OpenAPI spec version: 3.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'date'

module Teleswagger
  class InlineType
    
    ARTICLE = "article".freeze
    AUDIO = "audio".freeze
    CONTACT = "contact".freeze
    GAME = "game".freeze
    DOCUMENT = "document".freeze
    GIF = "gif".freeze
    LOCATION = "location".freeze
    MPEG4_GIF = "mpeg4_gif".freeze
    PHOTO = "photo".freeze
    VENUE = "venue".freeze
    VIDEO = "video".freeze
    VOICE = "voice".freeze
    STICKER = "sticker".freeze
  end

end
