=begin
#Telegram bot API

#This is a swagger defenition for [Telegram bot API](https://core.telegram.org/bots/api). 

OpenAPI spec version: 3.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'date'

module Teleswagger

  class SendInvoiceBody
    attr_accessor :chat_id

    attr_accessor :title

    attr_accessor :description

    attr_accessor :payload

    attr_accessor :provider_token

    attr_accessor :start_parameter

    attr_accessor :currency

    attr_accessor :prices

    attr_accessor :photo_url

    attr_accessor :photo_size

    attr_accessor :photo_width

    attr_accessor :photo_height

    attr_accessor :need_name

    attr_accessor :need_phone_number

    attr_accessor :need_email

    attr_accessor :need_shipping_address

    attr_accessor :is_flexible

    attr_accessor :disable_notification

    attr_accessor :reply_to_message_id

    attr_accessor :reply_markup


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'chat_id' => :'chat_id',
        :'title' => :'title',
        :'description' => :'description',
        :'payload' => :'payload',
        :'provider_token' => :'provider_token',
        :'start_parameter' => :'start_parameter',
        :'currency' => :'currency',
        :'prices' => :'prices',
        :'photo_url' => :'photo_url',
        :'photo_size' => :'photo_size',
        :'photo_width' => :'photo_width',
        :'photo_height' => :'photo_height',
        :'need_name' => :'need_name',
        :'need_phone_number' => :'need_phone_number',
        :'need_email' => :'need_email',
        :'need_shipping_address' => :'need_shipping_address',
        :'is_flexible' => :'is_flexible',
        :'disable_notification' => :'disable_notification',
        :'reply_to_message_id' => :'reply_to_message_id',
        :'reply_markup' => :'reply_markup'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'chat_id' => :'Integer',
        :'title' => :'String',
        :'description' => :'String',
        :'payload' => :'String',
        :'provider_token' => :'String',
        :'start_parameter' => :'String',
        :'currency' => :'String',
        :'prices' => :'Array<LabeledPrice>',
        :'photo_url' => :'String',
        :'photo_size' => :'Integer',
        :'photo_width' => :'Integer',
        :'photo_height' => :'Integer',
        :'need_name' => :'BOOLEAN',
        :'need_phone_number' => :'BOOLEAN',
        :'need_email' => :'BOOLEAN',
        :'need_shipping_address' => :'BOOLEAN',
        :'is_flexible' => :'BOOLEAN',
        :'disable_notification' => :'BOOLEAN',
        :'reply_to_message_id' => :'Integer',
        :'reply_markup' => :'Object'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'chat_id')
        self.chat_id = attributes[:'chat_id']
      end

      if attributes.has_key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.has_key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.has_key?(:'payload')
        self.payload = attributes[:'payload']
      end

      if attributes.has_key?(:'provider_token')
        self.provider_token = attributes[:'provider_token']
      end

      if attributes.has_key?(:'start_parameter')
        self.start_parameter = attributes[:'start_parameter']
      end

      if attributes.has_key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.has_key?(:'prices')
        if (value = attributes[:'prices']).is_a?(Array)
          self.prices = value
        end
      end

      if attributes.has_key?(:'photo_url')
        self.photo_url = attributes[:'photo_url']
      end

      if attributes.has_key?(:'photo_size')
        self.photo_size = attributes[:'photo_size']
      end

      if attributes.has_key?(:'photo_width')
        self.photo_width = attributes[:'photo_width']
      end

      if attributes.has_key?(:'photo_height')
        self.photo_height = attributes[:'photo_height']
      end

      if attributes.has_key?(:'need_name')
        self.need_name = attributes[:'need_name']
      end

      if attributes.has_key?(:'need_phone_number')
        self.need_phone_number = attributes[:'need_phone_number']
      end

      if attributes.has_key?(:'need_email')
        self.need_email = attributes[:'need_email']
      end

      if attributes.has_key?(:'need_shipping_address')
        self.need_shipping_address = attributes[:'need_shipping_address']
      end

      if attributes.has_key?(:'is_flexible')
        self.is_flexible = attributes[:'is_flexible']
      end

      if attributes.has_key?(:'disable_notification')
        self.disable_notification = attributes[:'disable_notification']
      end

      if attributes.has_key?(:'reply_to_message_id')
        self.reply_to_message_id = attributes[:'reply_to_message_id']
      end

      if attributes.has_key?(:'reply_markup')
        self.reply_markup = attributes[:'reply_markup']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @chat_id.nil?
        invalid_properties.push("invalid value for 'chat_id', chat_id cannot be nil.")
      end

      if @title.nil?
        invalid_properties.push("invalid value for 'title', title cannot be nil.")
      end

      if @description.nil?
        invalid_properties.push("invalid value for 'description', description cannot be nil.")
      end

      if @payload.nil?
        invalid_properties.push("invalid value for 'payload', payload cannot be nil.")
      end

      if @provider_token.nil?
        invalid_properties.push("invalid value for 'provider_token', provider_token cannot be nil.")
      end

      if @start_parameter.nil?
        invalid_properties.push("invalid value for 'start_parameter', start_parameter cannot be nil.")
      end

      if @currency.nil?
        invalid_properties.push("invalid value for 'currency', currency cannot be nil.")
      end

      if @prices.nil?
        invalid_properties.push("invalid value for 'prices', prices cannot be nil.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @chat_id.nil?
      return false if @title.nil?
      return false if @description.nil?
      return false if @payload.nil?
      return false if @provider_token.nil?
      return false if @start_parameter.nil?
      return false if @currency.nil?
      return false if @prices.nil?
      return true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          chat_id == o.chat_id &&
          title == o.title &&
          description == o.description &&
          payload == o.payload &&
          provider_token == o.provider_token &&
          start_parameter == o.start_parameter &&
          currency == o.currency &&
          prices == o.prices &&
          photo_url == o.photo_url &&
          photo_size == o.photo_size &&
          photo_width == o.photo_width &&
          photo_height == o.photo_height &&
          need_name == o.need_name &&
          need_phone_number == o.need_phone_number &&
          need_email == o.need_email &&
          need_shipping_address == o.need_shipping_address &&
          is_flexible == o.is_flexible &&
          disable_notification == o.disable_notification &&
          reply_to_message_id == o.reply_to_message_id &&
          reply_markup == o.reply_markup
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [chat_id, title, description, payload, provider_token, start_parameter, currency, prices, photo_url, photo_size, photo_width, photo_height, need_name, need_phone_number, need_email, need_shipping_address, is_flexible, disable_notification, reply_to_message_id, reply_markup].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = Teleswagger.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
